version: '3.8'
services:
  database:
    build: ../app/database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
      PGPORT: 5432
    ports:
    - 5432:5432
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U postgres -p 5432
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build: ../app/backend
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DATABASE_URL: postgres://postgres:postgres@database:5432/app
      PORT: 8082
    ports:
    - 3000:8082
    depends_on:
      database:
        condition: service_healthy
  frontend:
    build: ../app/frontend
    environment:
      VITE_API_PROXY_TARGET: http://backend:8082
    ports:
    - 8000:3000
    depends_on:
    - backend
volumes:
  postgres_data: null
